#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
Code generator for proto definitions, enum converters, and settings, problem, solution conversions.

Reads field_registry.yaml and generates:
  1. cuopt_remote_data.proto — full proto: enums, OptimizationProblem, settings, solutions,
     ChunkedResultHeader
  2. Enum converter C++ switch functions (.inc)
  3. Settings conversion C++ function bodies (.inc)
  4. Solution conversion C++ function bodies (.inc) — all 8 solution mapper functions
  5. Problem conversion C++ function bodies (.inc)

Usage:
  python generate_conversions.py [--registry field_registry.yaml] [--output-dir .] [--auto-number]
"""

import argparse
import os
import re
import sys
from pathlib import Path

import yaml

# ============================================================================
# Utilities
# ============================================================================

HEADER = """\
// ============================================================================
// AUTO-GENERATED by src/grpc/codegen/generate_conversions.py from field_registry.yaml
// DO NOT EDIT MANUALLY — regenerate with: python generate_conversions.py
// ============================================================================
"""


def write_file(path, content):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {path}")


def parse_field(entry):
    """Parse a field entry from the YAML, which may be a bare string or a dict.

    Does NOT set a default 'type' — callers supply context-appropriate defaults
    (e.g. "double" for scalars, "repeated double" for arrays).
    """
    if isinstance(entry, str):
        return {"name": entry}
    if isinstance(entry, dict):
        assert len(entry) == 1, f"Expected single-key dict, got {entry}"
        name = next(iter(entry))
        val = entry[name]
        if isinstance(val, str):
            return {"name": name, "type": val}
        if isinstance(val, dict):
            result = {"name": name}
            result.update(val)
            return result
        if val is None:
            return {"name": name}
    raise ValueError(f"Unexpected field format: {entry}")


def parse_settings_fields(entries, prefix=""):
    """Parse settings fields, handling nested sub-structs (e.g. tolerances)."""
    for entry in entries:
        assert isinstance(entry, dict) and len(entry) == 1
        name = next(iter(entry))
        val = entry[name]
        if isinstance(val, list):
            yield from parse_settings_fields(val, prefix=f"{prefix}{name}.")
        else:
            f = parse_field(entry)
            if prefix or "member" not in f:
                f["member"] = f"{prefix}{name}" if prefix else name
            yield f


def parse_enum_entry(entry, index=0):
    """Parse a single enum value entry.

    Supports three forms:
      - bare string 'CppName'        → (name, index)
      - {CppName: null}              → (name, index)
      - {CppName: number}            → (name, number)

    The caller is responsible for tracking the running counter; explicit values
    reset it (C-style enum semantics).
    """
    if isinstance(entry, str):
        return entry, index
    assert isinstance(entry, dict) and len(entry) == 1
    name = next(iter(entry))
    num = entry[name]
    return name, num if num is not None else index


def parse_enum_values(values):
    """Parse a full enum values list with C-style auto-numbering.

    Bare names get the next sequential number; explicit {Name: N} overrides
    reset the counter so the next bare name gets N+1.
    """
    counter = 0
    result = []
    for entry in values:
        name, num = parse_enum_entry(entry, index=counter)
        result.append((name, num))
        counter = num + 1
    return result


def camel_to_upper_snake(name):
    """Convert CamelCase to UPPER_SNAKE_CASE: PrimalInfeasible -> PRIMAL_INFEASIBLE."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    return s.upper()


def proto_type(t):
    """Map YAML type to proto type."""
    return {
        "double": "double",
        "float": "float",
        "int32": "int32",
        "int64": "int64",
        "bool": "bool",
        "string": "string",
        "bytes": "bytes",
    }.get(t, t)


def _from_proto_cast(ftype):
    """Return C++ cast for reading a proto field back into template type."""
    if ftype in ("double", "float"):
        return "f_t"
    if ftype in ("int32", "int64"):
        return "i_t"
    return None


def _array_element_cast(ftype):
    """Cast for serializing array elements to proto (to_proto direction)."""
    if "double" in ftype:
        return "double"
    if "int32" in ftype:
        return "int32_t"
    return None


def _array_cpp_type(ftype):
    """C++ vector element type for proto-to-C++ direction."""
    if "double" in ftype:
        return "f_t"
    if "int32" in ftype:
        return "i_t"
    return None


def _default_element_size(f):
    """Default element byte size for a field."""
    if "element_size" in f:
        return f["element_size"]
    ftype = f.get("type", "repeated double")
    if "int32" in ftype:
        return 4
    if ftype in ("bytes", "repeated string"):
        return 1
    if ftype.startswith("repeated ") and ftype.split()[-1] not in (
        "double",
        "int32",
        "string",
    ):
        return 4
    return 8


# ============================================================================
# Enum helpers — convention-based derivation
# ============================================================================

KNOWN_ACRONYMS = {"pdlp", "mip", "lp", "qp", "vrp", "pdp", "tsp"}


def _snake_to_pascal(key):
    """Convert snake_case key to PascalCase, uppercasing known acronyms.

    pdlp_termination_status -> PDLPTerminationStatus
    lp_method               -> LPMethod
    variable_type           -> VariableType
    """
    return "".join(
        part.upper() if part in KNOWN_ACRONYMS else part.capitalize()
        for part in key.split("_")
    )


def _enum_proto_type(key, edef):
    """Derive proto enum type name: explicit or PascalCase from key."""
    return edef.get("proto_type", _snake_to_pascal(key))


def _enum_cpp_type(key, edef):
    """Derive C++ type: explicit or {key}_t."""
    return edef.get("cpp_type", f"{key}_t")


def _enum_default(key, edef):
    """Derive default value: explicit or first value name (proto3 zero-value)."""
    if "default" in edef:
        return edef["default"]
    first = edef["values"][0]
    name, _ = parse_enum_entry(first)
    return name


def _enum_to_proto_fn(key, _edef):
    """Derive to_proto function name: to_proto_{key}."""
    return f"to_proto_{key}"


def _enum_from_proto_fn(key, _edef):
    """Derive from_proto function name: from_proto_{key}."""
    return f"from_proto_{key}"


def _proto_enum_value_name(cpp_name, prefix):
    """Derive proto enum value name from C++ name and prefix."""
    if not prefix:
        return cpp_name
    return f"{prefix}_{camel_to_upper_snake(cpp_name)}"


def _lookup_enum(registry, type_name):
    """Find an enum definition in the registry by key name."""
    return registry.get("enums", {}).get(type_name)


def _is_enum_type(registry, type_name):
    """Check if a type name refers to a registered enum."""
    return type_name in registry.get("enums", {})


def _is_repeated_enum(registry, ftype):
    """Check if a type is 'repeated <enum_key>' and return enum key if so."""
    if ftype.startswith("repeated "):
        inner = ftype.split(None, 1)[1]
        if _is_enum_type(registry, inner):
            return inner
    return None


def _proto_cpp_name(name):
    """Protobuf lowercases all field names for C++ accessor methods."""
    return name.lower()


# ============================================================================
# Problem field helpers
# ============================================================================


def _problem_getter_root(f):
    """Get the getter root for a problem field (setter_getter_root or name)."""
    return f.get("setter_getter_root", f["name"])


def _default_problem_getter(f, is_scalar):
    """Default getter for an optimization_problem field."""
    if "getter" in f:
        return f["getter"]
    root = _problem_getter_root(f)
    if is_scalar:
        return f"get_{root}()"
    ftype = f.get("type", "repeated double")
    if ftype == "repeated string":
        return f"get_{root}()"
    return f"get_{root}_host()"


def _default_problem_setter(f):
    """Default setter name for an optimization_problem field."""
    if "setter" in f:
        return f["setter"]
    root = _problem_getter_root(f)
    return f"set_{root}"


def _find_problem_field(obj, name):
    """Find a field by name in the optimization_problem arrays list."""
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        if f["name"] == name:
            return f
    return None


def _field_array_id_name(f):
    """Derive ArrayFieldId enum name from field name: FIELD_{UPPER_SNAKE(name)}."""
    return f"FIELD_{f['name'].upper()}"


def _field_result_id_name(f, prefix=""):
    """Derive ResultFieldId enum name from field name: RESULT_{PREFIX_}{UPPER_SNAKE(name)}."""
    if prefix:
        return f"RESULT_{prefix}_{f['name'].upper()}"
    return f"RESULT_{f['name'].upper()}"


def _problem_field_proto_type(registry, ftype):
    """Map optimization_problem field type to proto type."""
    if not ftype:
        return "double"
    enum_key = _is_repeated_enum(registry, ftype)
    if enum_key:
        edef = _lookup_enum(registry, enum_key)
        return f"repeated {_enum_proto_type(enum_key, edef)}"
    if ftype in (
        "repeated double",
        "repeated int32",
        "repeated string",
        "bytes",
    ):
        return ftype
    edef = _lookup_enum(registry, ftype)
    if edef:
        return _enum_proto_type(ftype, edef)
    return proto_type(ftype)


def _settings_field_proto_type(registry, f):
    """Map settings field type to proto type."""
    ftype = f.get("type", "double")
    edef = _lookup_enum(registry, ftype)
    if edef:
        return _enum_proto_type(ftype, edef)
    return proto_type(ftype)


def _solution_scalar_proto_type(registry, f):
    """Map solution scalar type to proto type."""
    ftype = f.get("type", "double")
    edef = _lookup_enum(registry, ftype)
    if edef:
        return _enum_proto_type(ftype, edef)
    return proto_type(ftype)


# ============================================================================
# Enum generation
# ============================================================================


def generate_enum_proto_from_registry(registry):
    """Generate all enum definitions for the proto file.

    Skips enum entries without 'values' (e.g. result_field_id which is
    auto-derived and only carries aliases).
    """
    enums = registry.get("enums", {})
    blocks = []
    for key, edef in enums.items():
        if "values" not in edef:
            continue
        proto_type_name = _enum_proto_type(key, edef)
        prefix = edef.get("proto_prefix", "")
        lines = [f"enum {proto_type_name} {{"]
        for cpp_name, num in parse_enum_values(edef["values"]):
            pname = _proto_enum_value_name(cpp_name, prefix)
            lines.append(f"  {pname} = {num};")
        lines.append("}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def generate_enum_converters_inc(registry, domain=None):
    """Generate C++ to_proto/from_proto switch functions for enums.

    If domain is given, only emit converters for enums with that domain tag.
    If domain is None, emit all converters (backward compat).
    Skips enum entries without 'values' (auto-derived enums like result_field_id).
    """
    enums = registry.get("enums", {})
    funcs = []
    for key, edef in enums.items():
        if "values" not in edef:
            continue
        if domain is not None and edef.get("domain") != domain:
            continue
        cpp_type = _enum_cpp_type(key, edef)
        proto_type_name = _enum_proto_type(key, edef)
        to_fn = _enum_to_proto_fn(key, edef)
        from_fn = _enum_from_proto_fn(key, edef)
        prefix = edef.get("proto_prefix", "")
        default_cpp = _enum_default(key, edef)
        default_proto = _proto_enum_value_name(default_cpp, prefix)

        # to_proto
        lines = [
            f"cuopt::remote::{proto_type_name} {to_fn}({cpp_type} v)",
            "{",
            "  switch (v) {",
        ]
        for cpp_name, _ in parse_enum_values(edef["values"]):
            pname = _proto_enum_value_name(cpp_name, prefix)
            lines.append(
                f"    case {cpp_type}::{cpp_name}: return cuopt::remote::{pname};"
            )
        lines.append(f"    default: return cuopt::remote::{default_proto};")
        lines.extend(["  }", "}"])
        funcs.append("\n".join(lines))

        # from_proto
        lines = [
            f"{cpp_type} {from_fn}(cuopt::remote::{proto_type_name} v)",
            "{",
            "  switch (v) {",
        ]
        for cpp_name, _ in parse_enum_values(edef["values"]):
            pname = _proto_enum_value_name(cpp_name, prefix)
            lines.append(
                f"    case cuopt::remote::{pname}: return {cpp_type}::{cpp_name};"
            )
        lines.append(f"    default: return {cpp_type}::{default_cpp};")
        lines.extend(["  }", "}"])
        funcs.append("\n".join(lines))

    return "\n\n".join(funcs)


# ============================================================================
# Proto file generation — ResultFieldId, ArrayFieldId, messages
# ============================================================================


def generate_proto_result_enums(registry):
    """Generate ResultFieldId enum entries (sorted by array_id).

    Primary entries are auto-derived from solution/warm-start array_id fields.
    Aliases come from enums.result_field_id.aliases in the registry, providing
    backward-compatible names for existing clients.
    """
    entries = []
    for obj_name in ["lp_solution", "mip_solution"]:
        obj = registry.get(obj_name, {})
        for entry in obj.get("arrays", []):
            f = parse_field(entry)
            enum_id = _field_result_id_name(f)
            aid = f.get("array_id")
            if aid is not None:
                entries.append((aid, f"  {enum_id} = {aid};"))
        ws = obj.get("warm_start", {})
        ws_rid_prefix = ws.get("result_id_prefix", "")
        for entry in ws.get("arrays", []):
            f = parse_field(entry)
            enum_id = _field_result_id_name(f, prefix=ws_rid_prefix)
            aid = f.get("array_id")
            if aid is not None:
                entries.append((aid, f"  {enum_id} = {aid};"))
    entries.sort(key=lambda x: x[0])
    seen, lines = set(), []
    for _, line in entries:
        eid = line.split(" = ")[0].strip()
        if eid not in seen:
            lines.append(line)
            seen.add(eid)

    rfid_enum = registry.get("enums", {}).get("result_field_id", {})
    alias_map = rfid_enum.get("aliases", {})
    if alias_map:
        alias_lines = sorted(
            (v, f"  {k} = {v};") for k, v in alias_map.items()
        )
        lines.insert(0, "  option allow_alias = true;")
        for _, line in alias_lines:
            lines.append(line)
    return "\n".join(lines)


def generate_array_field_id_enum(registry):
    """Generate ArrayFieldId enum for the proto file."""
    obj = registry.get("optimization_problem", {})
    entries = []
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        afid = _field_array_id_name(f)
        afnum = f.get("array_id")
        if afnum is not None:
            entries.append((afnum, f"  {afid} = {afnum};"))
    entries.sort(key=lambda x: x[0])
    return "\n".join(e[1] for e in entries)


def generate_array_field_element_size_inc(registry):
    """Generate body of array_field_element_size() switch function."""
    obj = registry.get("optimization_problem", {})
    cases_by_size = {}
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        afid = _field_array_id_name(f)
        size = _default_element_size(f)
        cases_by_size.setdefault(size, []).append(afid)
    lines = ["  switch (field_id) {"]
    for size in sorted(cases_by_size.keys()):
        if size == 8:
            continue
        for afid in cases_by_size[size]:
            lines.append(f"    case cuopt::remote::{afid}:")
        lines.append(f"      return {size};")
    lines.append("    default: return 8;")
    lines.append("  }")
    return "\n".join(lines)


# ============================================================================
# Settings proto + conversion generation
# ============================================================================


def generate_settings_message_proto(registry, message_name, obj):
    lines = []
    for f in parse_settings_fields(obj.get("fields", [])):
        num = f.get("field_num")
        if num is None:
            continue
        ptype = _settings_field_proto_type(registry, f)
        lines.append((num, f"  {ptype} {f['name']} = {num};"))
    if message_name == "PDLPSolverSettings":
        lines.append((50, "  PDLPWarmStartData warm_start_data = 50;"))
    lines.sort(key=lambda x: x[0])
    return "\n".join(item[1] for item in lines)


def generate_settings_to_proto_body(registry, obj_name, obj, indent="  "):
    lines, ind = [], indent
    for f in parse_settings_fields(obj.get("fields", [])):
        name, ftype = f["name"], f.get("type", "double")
        pname = _proto_cpp_name(name)
        cpp_member = f.get("member", f["name"])
        sentinel = f.get("sentinel")
        to_proto_cast = f.get("to_proto_cast")

        edef = _lookup_enum(registry, ftype)
        to_fn = _enum_to_proto_fn(ftype, edef) if edef else None

        if sentinel:
            sv, pv = sentinel["to_proto"], sentinel["proto_value"]
            lines.append(f"{ind}if (settings.{cpp_member} == {sv}) {{")
            lines.append(f"{ind}  pb_settings->set_{pname}({pv});")
            lines.append(f"{ind}}} else {{")
            cast = to_proto_cast or ("int64_t" if ftype == "int64" else None)
            expr = (
                f"static_cast<{cast}>(settings.{cpp_member})"
                if cast
                else f"settings.{cpp_member}"
            )
            lines.append(f"{ind}  pb_settings->set_{pname}({expr});")
            lines.append(f"{ind}}}")
        elif to_fn:
            lines.append(
                f"{ind}pb_settings->set_{pname}({to_fn}(settings.{cpp_member}));"
            )
        elif to_proto_cast:
            lines.append(
                f"{ind}pb_settings->set_{pname}(static_cast<{to_proto_cast}>(settings.{cpp_member}));"
            )
        else:
            lines.append(
                f"{ind}pb_settings->set_{pname}(settings.{cpp_member});"
            )
    return "\n".join(lines)


def generate_proto_to_settings_body(registry, obj_name, obj, indent="  "):
    lines, ind = [], indent
    for f in parse_settings_fields(obj.get("fields", [])):
        name, ftype = f["name"], f.get("type", "double")
        pname = _proto_cpp_name(name)
        cpp_member = f.get("member", f["name"])
        from_proto_cast = f.get("from_proto_cast")
        sentinel = f.get("sentinel")

        edef = _lookup_enum(registry, ftype)
        from_fn = _enum_from_proto_fn(ftype, edef) if edef else None

        if sentinel:
            guard = sentinel["from_proto_guard"]
            cast = sentinel.get("from_proto_cast", from_proto_cast)
            lines.append(f"{ind}if (pb_settings.{pname}() {guard}) {{")
            expr = (
                f"static_cast<{cast}>(pb_settings.{pname}())"
                if cast
                else f"pb_settings.{pname}()"
            )
            lines.append(f"{ind}  settings.{cpp_member} = {expr};")
            lines.append(f"{ind}}}")
        elif from_fn:
            lines.append(
                f"{ind}settings.{cpp_member} = {from_fn}(pb_settings.{pname}());"
            )
        elif from_proto_cast:
            lines.append(
                f"{ind}settings.{cpp_member} = static_cast<{from_proto_cast}>(pb_settings.{pname}());"
            )
        else:
            lines.append(
                f"{ind}settings.{cpp_member} = pb_settings.{pname}();"
            )
    return "\n".join(lines)


# ============================================================================
# Proto message generation — WarmStart, LPSolution, MIPSolution
# ============================================================================


def generate_warm_start_message_proto(registry):
    obj = registry.get("lp_solution", {}).get("warm_start", {})
    lines = []
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            lines.append((num, f"  repeated double {f['name']} = {num};"))
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            lines.append(
                (
                    num,
                    f"  {proto_type(f.get('type', 'double'))} {f['name']} = {num};",
                )
            )
    lines.sort(key=lambda x: x[0])
    return "\n".join(item[1] for item in lines)


def generate_lp_solution_message_proto(registry):
    obj = registry.get("lp_solution", {})
    lines = []
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            lines.append((num, f"  repeated double {f['name']} = {num};"))
    lines.append((4, "  PDLPWarmStartData warm_start_data = 4;"))
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            ptype = _solution_scalar_proto_type(registry, f)
            lines.append((num, f"  {ptype} {f['name']} = {num};"))
    lines.sort(key=lambda x: x[0])
    return "\n".join(item[1] for item in lines)


def generate_mip_solution_message_proto(registry):
    obj = registry.get("mip_solution", {})
    lines = []
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            lines.append((num, f"  repeated double {f['name']} = {num};"))
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            ptype = _solution_scalar_proto_type(registry, f)
            lines.append((num, f"  {ptype} {f['name']} = {num};"))
    lines.sort(key=lambda x: x[0])
    return "\n".join(item[1] for item in lines)


def generate_optimization_problem_proto(registry):
    obj = registry.get("optimization_problem", {})
    if not obj:
        return ""
    lines = []
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            ptype = _problem_field_proto_type(
                registry, f.get("type", "double")
            )
            lines.append((num, f"  {ptype} {f['name']} = {num};"))
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        num = f.get("field_num")
        if num is not None:
            ptype = _problem_field_proto_type(
                registry, f.get("type", "repeated double")
            )
            lines.append((num, f"  {ptype} {f['name']} = {num};"))
    lines.sort(key=lambda x: x[0])
    return "\n".join(item[1] for item in lines)


def generate_chunked_result_header_proto(registry):
    pc_enum = _enum_proto_type(
        "problem_category", registry["enums"]["problem_category"]
    )
    lines = [(1, f"  {pc_enum} problem_category = 1;")]
    for obj_name in ["lp_solution", "mip_solution"]:
        obj = registry.get(obj_name, {})
        for entry in obj.get("scalars", []):
            f = parse_field(entry)
            num = f.get("field_num")
            if num is not None:
                ptype = _solution_scalar_proto_type(registry, f)
                lines.append((num, f"  {ptype} {f['name']} = {num};"))
        ws = obj.get("warm_start", {})
        ws_ch_prefix = ws.get("chunked_header_prefix", "")
        for entry in ws.get("scalars", []):
            f = parse_field(entry)
            num = f.get("field_num")
            if num is not None:
                ch_name = f"{ws_ch_prefix}{f['name']}"
                lines.append(
                    (
                        num,
                        f"  {proto_type(f.get('type', 'double'))} {ch_name} = {num};",
                    )
                )
    lines.append((50, "  repeated ResultArrayDescriptor arrays = 50;"))
    lines.sort(key=lambda x: x[0])
    return "\n".join(item[1] for item in lines)


# ============================================================================
# Full data proto assembly
# ============================================================================


def generate_data_proto(registry):
    enums = generate_enum_proto_from_registry(registry)
    rfid = (
        "enum ResultFieldId {\n"
        + generate_proto_result_enums(registry)
        + "\n}"
    )
    opt_prob = ""
    if "optimization_problem" in registry:
        opt_prob = (
            "message OptimizationProblem {\n"
            + generate_optimization_problem_proto(registry)
            + "\n}\n"
        )
    pdlp_s = (
        "message PDLPSolverSettings {\n"
        + generate_settings_message_proto(
            registry, "PDLPSolverSettings", registry["pdlp_settings"]
        )
        + "\n}"
    )
    mip_s = (
        "message MIPSolverSettings {\n"
        + generate_settings_message_proto(
            registry, "MIPSolverSettings", registry["mip_settings"]
        )
        + "\n}"
    )
    ws = (
        "message PDLPWarmStartData {\n"
        + generate_warm_start_message_proto(registry)
        + "\n}"
    )
    lp = (
        "message LPSolution {\n"
        + generate_lp_solution_message_proto(registry)
        + "\n}"
    )
    mip = (
        "message MIPSolution {\n"
        + generate_mip_solution_message_proto(registry)
        + "\n}"
    )
    rad = (
        "message ResultArrayDescriptor {\n"
        "  ResultFieldId field_id = 1;\n"
        "  int64 total_elements = 2;\n"
        "  int64 element_size_bytes = 3;\n"
        "}"
    )
    ch = (
        "message ChunkedResultHeader {\n"
        + generate_chunked_result_header_proto(registry)
        + "\n}"
    )
    afid = ""
    if "optimization_problem" in registry:
        afid_body = generate_array_field_id_enum(registry)
        if afid_body:
            afid = "enum ArrayFieldId {\n" + afid_body + "\n}\n"
    parts = [
        "// AUTO-GENERATED by src/grpc/codegen/generate_conversions.py from field_registry.yaml",
        "// DO NOT EDIT — regenerate with: python cpp/src/grpc/codegen/generate_conversions.py",
        "",
        'syntax = "proto3";',
        "",
        "package cuopt.remote;",
        "",
        enums,
        "",
        rfid,
        "",
        afid,
        opt_prob,
        pdlp_s,
        "",
        mip_s,
        "",
        ws,
        "",
        lp,
        "",
        mip,
        "",
        rad,
        "",
        ch,
        "",
    ]
    return "\n".join(parts)


# ============================================================================
# Solution conversion code generation
# ============================================================================


def _gen_solution_to_proto(registry, obj_name, obj, indent="  "):
    """Generate body of map_{lp,mip}_solution_to_proto()."""
    ind = indent
    lines = []

    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        getter = f.get("getter", f"get_{name}()")
        to_cast = f.get("to_proto_cast")
        edef = _lookup_enum(registry, f.get("type", "double"))
        if edef:
            to_fn = _enum_to_proto_fn(f["type"], edef)
            lines.append(
                f"{ind}pb_solution->set_{pname}({to_fn}(solution.{getter}));"
            )
        elif to_cast:
            lines.append(
                f"{ind}pb_solution->set_{pname}(static_cast<{to_cast}>(solution.{getter}));"
            )
        else:
            lines.append(f"{ind}pb_solution->set_{pname}(solution.{getter});")

    lines.append("")

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        pname = _proto_cpp_name(f["name"])
        getter = f.get("getter", f"get_{f['name']}_host()")
        var = f"_{f['name']}"
        lines.append(f"{ind}const auto& {var} = solution.{getter};")
        lines.append(
            f"{ind}for (const auto& v : {var}) pb_solution->add_{pname}(static_cast<double>(v));"
        )

    # Warm start
    ws = obj.get("warm_start")
    if ws:
        check = ws.get("presence_check", "has_warm_start_data()")
        ws_getter = ws.get("getter", "get_cpu_pdlp_warm_start_data()")
        lines.append("")
        lines.append(f"{ind}if (solution.{check}) {{")
        lines.append(
            f"{ind}  auto* pb_ws = pb_solution->mutable_warm_start_data();"
        )
        lines.append(f"{ind}  const auto& ws = solution.{ws_getter};")
        for entry in ws.get("arrays", []):
            f = parse_field(entry)
            pname = _proto_cpp_name(f["name"])
            member = f.get("member", f["name"])
            lines.append(
                f"{ind}  for (const auto& v : ws.{member}) pb_ws->add_{pname}(static_cast<double>(v));"
            )
        for entry in ws.get("scalars", []):
            f = parse_field(entry)
            pname = _proto_cpp_name(f["name"])
            member = f.get("member", f["name"])
            ftype = f.get("type", "double")
            cast = (
                "double"
                if ftype == "double"
                else ("int32_t" if ftype == "int32" else "double")
            )
            lines.append(
                f"{ind}  pb_ws->set_{pname}(static_cast<{cast}>(ws.{member}));"
            )
        lines.append(f"{ind}}}")

    return "\n".join(lines)


def _gen_proto_to_solution(registry, obj_name, obj, indent="  "):
    """Generate body of map_proto_to_{lp,mip}_solution()."""
    ind = indent
    lines = []
    cpp_type = obj["cpp_type"]
    constructor_args = obj.get("constructor_args", {})
    ws = obj.get("warm_start")

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        pname = _proto_cpp_name(f["name"])
        lines.append(
            f"{ind}std::vector<f_t> {f['name']}(pb_solution.{pname}().begin(), pb_solution.{pname}().end());"
        )

    lines.append("")

    scalar_vars = {}
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        if f.get("proto_only"):
            continue
        ftype = f.get("type", "double")
        from_cast = f.get("from_proto_cast")
        edef = _lookup_enum(registry, ftype)
        if edef:
            from_fn = _enum_from_proto_fn(ftype, edef)
            lines.append(
                f"{ind}auto _{name} = {from_fn}(pb_solution.{pname}());"
            )
        elif from_cast:
            lines.append(
                f"{ind}auto _{name} = static_cast<{from_cast}>(pb_solution.{pname}());"
            )
        else:
            cast = _from_proto_cast(ftype)
            if cast:
                lines.append(
                    f"{ind}auto _{name} = static_cast<{cast}>(pb_solution.{pname}());"
                )
            else:
                lines.append(f"{ind}auto _{name} = pb_solution.{pname}();")
        scalar_vars[name] = f"_{name}"

    array_names = [parse_field(e)["name"] for e in obj.get("arrays", [])]
    arg_scalars = constructor_args.get("scalars", [])
    args = [f"std::move({n})" for n in array_names]
    args += [scalar_vars.get(s, f"_{s}") for s in arg_scalars]

    # Warm start
    if ws:
        accessor_getter = "warm_start_data"
        lines.append("")
        lines.append(f"{ind}if (pb_solution.has_{accessor_getter}()) {{")
        lines.append(
            f"{ind}  const auto& pb_ws = pb_solution.{accessor_getter}();"
        )
        lines.append(f"{ind}  cpu_pdlp_warm_start_data_t<i_t, f_t> ws;")

        for entry in ws.get("arrays", []):
            f = parse_field(entry)
            pname = _proto_cpp_name(f["name"])
            member = f.get("member", f["name"])
            lines.append(
                f"{ind}  ws.{member}.assign(pb_ws.{pname}().begin(), pb_ws.{pname}().end());"
            )

        for entry in ws.get("scalars", []):
            f = parse_field(entry)
            pname = _proto_cpp_name(f["name"])
            member = f.get("member", f["name"])
            ftype = f.get("type", "double")
            cast = _from_proto_cast(ftype)
            if cast:
                lines.append(
                    f"{ind}  ws.{member} = static_cast<{cast}>(pb_ws.{pname}());"
                )
            else:
                lines.append(f"{ind}  ws.{member} = pb_ws.{pname}();")

        ws_args = args + ["std::move(ws)"]
        lines.append(f"{ind}  return {cpp_type}({', '.join(ws_args)});")
        lines.append(f"{ind}}}")
        lines.append("")

    lines.append(f"{ind}return {cpp_type}({', '.join(args)});")
    return "\n".join(lines)


def _gen_chunked_header(registry, obj_name, obj, indent="  "):
    """Generate body of populate_chunked_result_header_{lp,mip}()."""
    ind = indent
    lines = []
    category = "MIP" if obj_name == "mip_solution" else "LP"
    lines.append(
        f"{ind}header->set_problem_category(cuopt::remote::{category});"
    )

    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        getter = f.get("getter", f"get_{name}()")
        to_cast = f.get("to_proto_cast")
        edef = _lookup_enum(registry, f.get("type", "double"))
        if edef:
            to_fn = _enum_to_proto_fn(f["type"], edef)
            lines.append(
                f"{ind}header->set_{pname}({to_fn}(solution.{getter}));"
            )
        elif to_cast:
            lines.append(
                f"{ind}header->set_{pname}(static_cast<{to_cast}>(solution.{getter}));"
            )
        else:
            lines.append(f"{ind}header->set_{pname}(solution.{getter});")

    lines.append("")

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        getter = f.get("getter", f"get_{f['name']}_host()")
        eid = _field_result_id_name(f)
        lines.append(
            f"{ind}add_result_array_descriptor(header, cuopt::remote::{eid}, solution.{getter}.size(), sizeof(double));"
        )

    # Warm start
    ws = obj.get("warm_start")
    if ws:
        check = ws.get("presence_check", "has_warm_start_data()")
        ws_getter = ws.get("getter", "get_cpu_pdlp_warm_start_data()")
        ws_ch_prefix = ws.get("chunked_header_prefix", "")
        ws_rid_prefix = ws.get("result_id_prefix", "")
        lines.append("")
        lines.append(f"{ind}if (solution.{check}) {{")
        lines.append(f"{ind}  const auto& ws = solution.{ws_getter};")
        for entry in ws.get("scalars", []):
            f = parse_field(entry)
            ch_name = f"{ws_ch_prefix}{f['name']}"
            pname = _proto_cpp_name(ch_name)
            member = f.get("member", f["name"])
            ftype = f.get("type", "double")
            cast = (
                "double"
                if ftype == "double"
                else ("int32_t" if ftype == "int32" else "double")
            )
            lines.append(
                f"{ind}  header->set_{pname}(static_cast<{cast}>(ws.{member}));"
            )
        lines.append("")
        for entry in ws.get("arrays", []):
            f = parse_field(entry)
            member = f.get("member", f["name"])
            eid = _field_result_id_name(f, prefix=ws_rid_prefix)
            lines.append(
                f"{ind}  add_result_array_descriptor(header, cuopt::remote::{eid}, ws.{member}.size(), sizeof(double));"
            )
        lines.append(f"{ind}}}")

    return "\n".join(lines)


def _gen_collect_arrays(registry, obj_name, obj, indent="  "):
    """Generate body of collect_{lp,mip}_solution_arrays()."""
    ind = indent
    lines = [f"{ind}std::map<int32_t, std::vector<uint8_t>> arrays;"]

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        getter = f.get("getter", f"get_{f['name']}_host()")
        eid = _field_result_id_name(f)
        var = f"_{f['name']}"
        lines.append(f"{ind}const auto& {var} = solution.{getter};")
        lines.append(
            f"{ind}if (!{var}.empty()) {{ arrays[cuopt::remote::{eid}] = doubles_to_bytes({var}); }}"
        )

    ws = obj.get("warm_start")
    if ws:
        check = ws.get("presence_check", "has_warm_start_data()")
        ws_getter = ws.get("getter", "get_cpu_pdlp_warm_start_data()")
        ws_rid_prefix = ws.get("result_id_prefix", "")
        lines.append(f"{ind}if (solution.{check}) {{")
        lines.append(f"{ind}  const auto& ws = solution.{ws_getter};")
        for entry in ws.get("arrays", []):
            f = parse_field(entry)
            member = f.get("member", f["name"])
            eid = _field_result_id_name(f, prefix=ws_rid_prefix)
            lines.append(
                f"{ind}  if (!ws.{member}.empty()) {{ arrays[cuopt::remote::{eid}] = doubles_to_bytes(ws.{member}); }}"
            )
        lines.append(f"{ind}}}")

    lines.append(f"{ind}return arrays;")
    return "\n".join(lines)


def _gen_chunked_to_solution(registry, obj_name, obj, indent="  "):
    """Generate body of chunked_result_to_{lp,mip}_solution()."""
    ind = indent
    lines = []
    constructor_args = obj.get("constructor_args", {})
    ws = obj.get("warm_start")

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        eid = _field_result_id_name(f)
        lines.append(
            f"{ind}auto {f['name']} = bytes_to_typed<f_t>(arrays, cuopt::remote::{eid});"
        )

    lines.append("")

    scalar_vars = {}
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        if f.get("proto_only"):
            continue
        ftype = f.get("type", "double")
        from_cast = f.get("from_proto_cast")
        edef = _lookup_enum(registry, ftype)
        if edef:
            from_fn = _enum_from_proto_fn(ftype, edef)
            lines.append(f"{ind}auto _{name} = {from_fn}(h.{pname}());")
        elif from_cast:
            lines.append(
                f"{ind}auto _{name} = static_cast<{from_cast}>(h.{pname}());"
            )
        else:
            cast = _from_proto_cast(ftype)
            if cast:
                lines.append(
                    f"{ind}auto _{name} = static_cast<{cast}>(h.{pname}());"
                )
            else:
                lines.append(f"{ind}auto _{name} = h.{pname}();")
        scalar_vars[name] = f"_{name}"

    array_names = [parse_field(e)["name"] for e in obj.get("arrays", [])]
    arg_scalars = constructor_args.get("scalars", [])
    args = [f"std::move({n})" for n in array_names]
    args += [scalar_vars.get(s, f"_{s}") for s in arg_scalars]

    # Warm start
    if ws:
        ws_arrays = ws.get("arrays", [])
        ws_rid_prefix = ws.get("result_id_prefix", "")
        ws_ch_prefix = ws.get("chunked_header_prefix", "")
        first_array = parse_field(ws_arrays[0]) if ws_arrays else None
        detect_eid = (
            _field_result_id_name(first_array, prefix=ws_rid_prefix)
            if first_array
            else None
        )
        lines.append("")
        lines.append(
            f"{ind}auto _ws_detect = bytes_to_typed<f_t>(arrays, cuopt::remote::{detect_eid});"
        )
        lines.append(f"{ind}if (!_ws_detect.empty()) {{")
        lines.append(f"{ind}  cpu_pdlp_warm_start_data_t<i_t, f_t> ws;")

        first = True
        for entry in ws_arrays:
            f = parse_field(entry)
            member = f.get("member", f["name"])
            eid = _field_result_id_name(f, prefix=ws_rid_prefix)
            if first:
                lines.append(f"{ind}  ws.{member} = std::move(_ws_detect);")
                first = False
            else:
                lines.append(
                    f"{ind}  ws.{member} = bytes_to_typed<f_t>(arrays, cuopt::remote::{eid});"
                )

        for entry in ws.get("scalars", []):
            f = parse_field(entry)
            ch_name = f"{ws_ch_prefix}{f['name']}"
            pname = _proto_cpp_name(ch_name)
            member = f.get("member", f["name"])
            ftype = f.get("type", "double")
            cast = _from_proto_cast(ftype)
            if cast:
                lines.append(
                    f"{ind}  ws.{member} = static_cast<{cast}>(h.{pname}());"
                )
            else:
                lines.append(f"{ind}  ws.{member} = h.{pname}();")

        cpp_type = obj["cpp_type"]
        ws_args = args + ["std::move(ws)"]
        lines.append(f"{ind}  return {cpp_type}({', '.join(ws_args)});")
        lines.append(f"{ind}}}")
        lines.append("")

    cpp_type = obj["cpp_type"]
    lines.append(f"{ind}return {cpp_type}({', '.join(args)});")
    return "\n".join(lines)


def _gen_estimate_size(registry, obj_name, obj, indent="  "):
    """Generate body of estimate_{lp,mip}_solution_proto_size()."""
    ind = indent
    lines = [f"{ind}size_t est = 0;"]

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        getter = f.get("getter", f"get_{f['name']}_host()")
        size_getter = getter.replace("_host()", "_size()")
        lines.append(
            f"{ind}est += static_cast<size_t>(solution.{size_getter}) * sizeof(double);"
        )

    ws = obj.get("warm_start")
    if ws:
        check = ws.get("presence_check", "has_warm_start_data()")
        ws_getter = ws.get("getter", "get_cpu_pdlp_warm_start_data()")
        lines.append(f"{ind}if (solution.{check}) {{")
        lines.append(f"{ind}  const auto& ws = solution.{ws_getter};")
        for entry in ws.get("arrays", []):
            f = parse_field(entry)
            member = f.get("member", f["name"])
            lines.append(f"{ind}  est += ws.{member}.size() * sizeof(double);")
        lines.append(f"{ind}}}")

    overhead = 512 if ws else 256
    lines.append(f"{ind}est += {overhead};")
    lines.append(f"{ind}return est;")
    return "\n".join(lines)


# ============================================================================
# Problem conversion code generation
# ============================================================================


def _gen_problem_to_proto(registry, indent="  "):
    """Generate body of map_problem_to_proto()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = []
    setter_groups = obj.get("setter_groups", {})
    grouped_fields = set()
    for gdef in setter_groups.values():
        for fname in gdef.get("fields", []):
            grouped_fields.add(fname)

    # Scalars
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        pname = _proto_cpp_name(f["name"])
        getter = _default_problem_getter(f, is_scalar=True)
        ftype = f.get("type", "double")
        edef = _lookup_enum(registry, ftype)
        if edef:
            to_fn = _enum_to_proto_fn(ftype, edef)
            lines.append(
                f"{ind}pb_problem->set_{pname}({to_fn}(cpu_problem.{getter}));"
            )
        else:
            lines.append(
                f"{ind}pb_problem->set_{pname}(cpu_problem.{getter});"
            )

    lines.append("")

    # Non-grouped arrays
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        if name in grouped_fields or f.get("skip_conversion"):
            continue
        ftype = f.get("type", "repeated double")
        getter = _default_problem_getter(f, is_scalar=False)

        enum_key = _is_repeated_enum(registry, ftype)
        if enum_key:
            edef = _lookup_enum(registry, enum_key)
            to_fn = _enum_to_proto_fn(enum_key, edef)
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto _{name} = cpu_problem.{getter};")
            lines.append(
                f"{ind}  for (const auto& v : _{name}) pb_problem->add_{pname}({to_fn}(v));"
            )
            lines.append(f"{ind}}}")
        elif ftype == "repeated string":
            lines.append(
                f"{ind}for (const auto& s : cpu_problem.{getter}) pb_problem->add_{pname}(s);"
            )
        elif ftype == "bytes":
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto _{name} = cpu_problem.{getter};")
            lines.append(f"{ind}  if (!_{name}.empty()) {{")
            lines.append(
                f"{ind}    pb_problem->set_{pname}(std::string(_{name}.begin(), _{name}.end()));"
            )
            lines.append(f"{ind}  }}")
            lines.append(f"{ind}}}")
        elif ftype.startswith("repeated"):
            cast = _array_element_cast(ftype)
            var = f"_{name}"
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto {var} = cpu_problem.{getter};")
            lines.append(
                f"{ind}  for (const auto& v : {var}) pb_problem->add_{pname}(static_cast<{cast}>(v));"
            )
            lines.append(f"{ind}}}")

    # Setter groups
    for gname, gdef in setter_groups.items():
        fields = [
            _find_problem_field(obj, fn) for fn in gdef.get("fields", [])
        ]
        for f in fields:
            if f is None:
                continue
            pname = _proto_cpp_name(f["name"])
            getter = _default_problem_getter(f, is_scalar=False)
            ftype = f.get("type", "repeated double")
            cast = _array_element_cast(ftype)
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto _{f['name']} = cpu_problem.{getter};")
            lines.append(
                f"{ind}  for (const auto& v : _{f['name']}) pb_problem->add_{pname}(static_cast<{cast}>(v));"
            )
            lines.append(f"{ind}}}")

    return "\n".join(lines)


def _gen_proto_to_problem(registry, indent="  "):
    """Generate body of map_proto_to_problem()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = []
    setter_groups = obj.get("setter_groups", {})
    grouped_fields = set()
    for gdef in setter_groups.values():
        for fname in gdef.get("fields", []):
            grouped_fields.add(fname)
    # Scalars
    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        setter = _default_problem_setter(f)
        ftype = f.get("type", "double")
        edef = _lookup_enum(registry, ftype)
        if edef:
            from_fn = _enum_from_proto_fn(ftype, edef)
            lines.append(
                f"{ind}cpu_problem.{setter}({from_fn}(pb_problem.{pname}()));"
            )
        else:
            lines.append(f"{ind}cpu_problem.{setter}(pb_problem.{pname}());")

    lines.append("")

    # Setter groups — guard on first field having data
    for gname, gdef in setter_groups.items():
        setter_name = gdef["setter"]
        fields = [
            _find_problem_field(obj, fn) for fn in gdef.get("fields", [])
        ]
        first = next((f for f in fields if f is not None), None)
        if first is None:
            continue
        first_pname = _proto_cpp_name(first["name"])
        lines.append(f"{ind}if (pb_problem.{first_pname}_size() > 0) {{")
        ii = ind + "  "

        for f in fields:
            if f is None:
                continue
            pname = _proto_cpp_name(f["name"])
            ftype = f.get("type", "repeated double")
            cpp_t = _array_cpp_type(ftype)
            lines.append(
                f"{ii}std::vector<{cpp_t}> {f['name']}(pb_problem.{pname}().begin(), pb_problem.{pname}().end());"
            )

        args = []
        for f in fields:
            if f is None:
                continue
            args.append(f"{f['name']}.data()")
            args.append(f"static_cast<i_t>({f['name']}.size())")
        lines.append(f"{ii}cpu_problem.{setter_name}({', '.join(args)});")
        lines.append(f"{ind}}}")
        lines.append("")

    # Non-grouped arrays
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        if name in grouped_fields or f.get("skip_conversion"):
            continue
        ftype = f.get("type", "repeated double")
        setter = _default_problem_setter(f)

        enum_key = _is_repeated_enum(registry, ftype)
        if enum_key:
            edef = _lookup_enum(registry, enum_key)
            from_fn = _enum_from_proto_fn(enum_key, edef)
            cpp_type = _enum_cpp_type(enum_key, edef)
            lines.append(f"{ind}if (pb_problem.{pname}_size() > 0) {{")
            lines.append(f"{ind}  std::vector<{cpp_type}> {name};")
            lines.append(f"{ind}  {name}.reserve(pb_problem.{pname}_size());")
            proto_type = _enum_proto_type(enum_key, edef)
            lines.append(
                f"{ind}  for (const auto& v : pb_problem.{pname}()) {{"
            )
            lines.append(
                f"{ind}    {name}.push_back({from_fn}(static_cast<cuopt::remote::{proto_type}>(v)));"
            )
            lines.append(f"{ind}  }}")
            lines.append(
                f"{ind}  cpu_problem.{setter}({name}.data(), static_cast<i_t>({name}.size()));"
            )
            lines.append(f"{ind}}}")
        elif ftype == "repeated string":
            lines.append(f"{ind}if (pb_problem.{pname}_size() > 0) {{")
            lines.append(
                f"{ind}  std::vector<std::string> {name}(pb_problem.{pname}().begin(), pb_problem.{pname}().end());"
            )
            lines.append(f"{ind}  cpu_problem.{setter}({name});")
            lines.append(f"{ind}}}")
        elif ftype == "bytes":
            lines.append(f"{ind}if (!pb_problem.{pname}().empty()) {{")
            lines.append(
                f"{ind}  const std::string& {name}_str = pb_problem.{pname}();"
            )
            lines.append(
                f"{ind}  cpu_problem.{setter}({name}_str.data(), static_cast<i_t>({name}_str.size()));"
            )
            lines.append(f"{ind}}}")
        elif ftype.startswith("repeated"):
            cpp_t = _array_cpp_type(ftype)
            guard = f.get("conditional")
            open_brace = (
                f"if (pb_problem.{pname}_size() > 0) {{" if guard else "{"
            )
            lines.append(f"{ind}{open_brace}")
            lines.append(
                f"{ind}  std::vector<{cpp_t}> {name}(pb_problem.{pname}().begin(), pb_problem.{pname}().end());"
            )
            lines.append(
                f"{ind}  cpu_problem.{setter}({name}.data(), static_cast<i_t>({name}.size()));"
            )
            lines.append(f"{ind}}}")

    return "\n".join(lines)


def _gen_estimate_problem_size(registry, indent="  "):
    """Generate body of estimate_problem_proto_size()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = [f"{ind}size_t est = 0;"]

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        if f.get("skip_conversion"):
            continue
        ftype = f.get("type", "repeated double")
        getter = _default_problem_getter(f, is_scalar=False)
        if ftype == "repeated string":
            lines.append(
                f"{ind}for (const auto& s : cpu_problem.{getter}) est += s.size() + 2;"
            )
        elif ftype == "bytes":
            lines.append(f"{ind}est += cpu_problem.{getter}.size();")
        elif "int32" in ftype:
            lines.append(f"{ind}est += cpu_problem.{getter}.size() * 5;")
        elif ftype.startswith("repeated ") and _is_repeated_enum(
            registry, ftype
        ):
            lines.append(f"{ind}est += cpu_problem.{getter}.size() * 4;")
        else:
            lines.append(
                f"{ind}est += cpu_problem.{getter}.size() * sizeof(double);"
            )

    lines.append(f"{ind}est += 512;")
    lines.append(f"{ind}return est;")
    return "\n".join(lines)


def _gen_populate_chunked_header(registry, solver_type, indent="  "):
    """Generate body of populate_chunked_header_{lp,mip}()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = []

    lines.append(f"{ind}auto* rh = header->mutable_header();")
    lines.append(f"{ind}rh->set_version(1);")
    if solver_type == "lp":
        lines.append(f"{ind}rh->set_problem_category(cuopt::remote::LP);")
    else:
        lines.append(f"{ind}rh->set_problem_category(cuopt::remote::MIP);")

    lines.append("")

    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        pname = _proto_cpp_name(f["name"])
        getter = _default_problem_getter(f, is_scalar=True)
        ftype = f.get("type", "double")
        edef = _lookup_enum(registry, ftype)
        if edef:
            to_fn = _enum_to_proto_fn(ftype, edef)
            lines.append(
                f"{ind}header->set_{pname}({to_fn}(cpu_problem.{getter}));"
            )
        else:
            lines.append(f"{ind}header->set_{pname}(cpu_problem.{getter});")

    lines.append("")

    if solver_type == "lp":
        lines.append(
            f"{ind}map_pdlp_settings_to_proto(settings, header->mutable_lp_settings());"
        )
    else:
        lines.append(
            f"{ind}map_mip_settings_to_proto(settings, header->mutable_mip_settings());"
        )
        lines.append(f"{ind}header->set_enable_incumbents(enable_incumbents);")

    return "\n".join(lines)


def _gen_chunked_header_to_problem(registry, indent="  "):
    """Generate body of map_chunked_header_to_problem()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = []

    for entry in obj.get("scalars", []):
        f = parse_field(entry)
        name = f["name"]
        pname = _proto_cpp_name(name)
        setter = _default_problem_setter(f)
        ftype = f.get("type", "double")
        edef = _lookup_enum(registry, ftype)
        if edef:
            from_fn = _enum_from_proto_fn(ftype, edef)
            lines.append(
                f"{ind}cpu_problem.{setter}({from_fn}(header.{pname}()));"
            )
        else:
            lines.append(f"{ind}cpu_problem.{setter}(header.{pname}());")

    lines.append("")

    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        if f.get("type") != "repeated string":
            continue
        name = f["name"]
        pname = _proto_cpp_name(name)
        setter = _default_problem_setter(f)
        lines.append(f"{ind}if (header.{pname}_size() > 0) {{")
        lines.append(
            f"{ind}  std::vector<std::string> {name}(header.{pname}().begin(), header.{pname}().end());"
        )
        lines.append(f"{ind}  cpu_problem.{setter}({name});")
        lines.append(f"{ind}}}")

    return "\n".join(lines)


def _gen_chunked_arrays_to_problem(registry, indent="  "):
    """Generate body of map_chunked_arrays_to_problem()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = []
    setter_groups = obj.get("setter_groups", {})
    grouped_fields = set()
    for gdef in setter_groups.values():
        for fname in gdef.get("fields", []):
            grouped_fields.add(fname)
    lines.append(f"{ind}map_chunked_header_to_problem(header, cpu_problem);")
    lines.append("")

    # Lambda helpers
    lines.append(
        f"{ind}auto get_doubles = [&](int32_t field_id) -> std::vector<f_t> {{"
    )
    lines.append(f"{ind}  auto it = arrays.find(field_id);")
    lines.append(
        f"{ind}  if (it == arrays.end() || it->second.empty()) return {{}};"
    )
    lines.append(
        f"{ind}  if (it->second.size() % sizeof(double) != 0) return {{}};"
    )
    lines.append(f"{ind}  size_t n = it->second.size() / sizeof(double);")
    lines.append(f"{ind}  if constexpr (std::is_same_v<f_t, double>) {{")
    lines.append(f"{ind}    std::vector<double> v(n);")
    lines.append(
        f"{ind}    std::memcpy(v.data(), it->second.data(), n * sizeof(double));"
    )
    lines.append(f"{ind}    return v;")
    lines.append(f"{ind}  }} else {{")
    lines.append(f"{ind}    std::vector<double> tmp(n);")
    lines.append(
        f"{ind}    std::memcpy(tmp.data(), it->second.data(), n * sizeof(double));"
    )
    lines.append(f"{ind}    return std::vector<f_t>(tmp.begin(), tmp.end());")
    lines.append(f"{ind}  }}")
    lines.append(f"{ind}}};")
    lines.append("")

    lines.append(
        f"{ind}auto get_ints = [&](int32_t field_id) -> std::vector<i_t> {{"
    )
    lines.append(f"{ind}  auto it = arrays.find(field_id);")
    lines.append(
        f"{ind}  if (it == arrays.end() || it->second.empty()) return {{}};"
    )
    lines.append(
        f"{ind}  if (it->second.size() % sizeof(int32_t) != 0) return {{}};"
    )
    lines.append(f"{ind}  size_t n = it->second.size() / sizeof(int32_t);")
    lines.append(f"{ind}  if constexpr (std::is_same_v<i_t, int32_t>) {{")
    lines.append(f"{ind}    std::vector<int32_t> v(n);")
    lines.append(
        f"{ind}    std::memcpy(v.data(), it->second.data(), n * sizeof(int32_t));"
    )
    lines.append(f"{ind}    return v;")
    lines.append(f"{ind}  }} else {{")
    lines.append(f"{ind}    std::vector<int32_t> tmp(n);")
    lines.append(
        f"{ind}    std::memcpy(tmp.data(), it->second.data(), n * sizeof(int32_t));"
    )
    lines.append(f"{ind}    return std::vector<i_t>(tmp.begin(), tmp.end());")
    lines.append(f"{ind}  }}")
    lines.append(f"{ind}}};")
    lines.append("")

    lines.append(
        f"{ind}auto get_bytes = [&](int32_t field_id) -> std::string {{"
    )
    lines.append(f"{ind}  auto it = arrays.find(field_id);")
    lines.append(
        f"{ind}  if (it == arrays.end() || it->second.empty()) return {{}};"
    )
    lines.append(
        f"{ind}  return std::string(reinterpret_cast<const char*>(it->second.data()), it->second.size());"
    )
    lines.append(f"{ind}}};")
    lines.append("")

    lines.append(
        f"{ind}auto get_string_list = [&](int32_t field_id) -> std::vector<std::string> {{"
    )
    lines.append(f"{ind}  auto it = arrays.find(field_id);")
    lines.append(
        f"{ind}  if (it == arrays.end() || it->second.empty()) return {{}};"
    )
    lines.append(f"{ind}  std::vector<std::string> names;")
    lines.append(
        f"{ind}  const char* s     = reinterpret_cast<const char*>(it->second.data());"
    )
    lines.append(f"{ind}  const char* s_end = s + it->second.size();")
    lines.append(f"{ind}  while (s < s_end) {{")
    lines.append(
        f"{ind}    const char* nul = static_cast<const char*>(std::memchr(s, '\\0', s_end - s));"
    )
    lines.append(f"{ind}    if (!nul) nul = s_end;")
    lines.append(f"{ind}    names.emplace_back(s, nul);")
    lines.append(f"{ind}    if (nul == s_end) break;")
    lines.append(f"{ind}    s = nul + 1;")
    lines.append(f"{ind}  }}")
    lines.append(f"{ind}  return names;")
    lines.append(f"{ind}}};")
    lines.append("")

    # Setter groups
    for gname, gdef in setter_groups.items():
        setter_name = gdef["setter"]
        fields = [
            _find_problem_field(obj, fn) for fn in gdef.get("fields", [])
        ]

        for f in fields:
            if f is None:
                continue
            ftype = f.get("type", "repeated double")
            afid = _field_array_id_name(f)
            extract_fn = "get_doubles" if "double" in ftype else "get_ints"
            lines.append(
                f"{ind}auto {f['name']} = {extract_fn}(cuopt::remote::{afid});"
            )

        guard_parts = [f"!{f['name']}.empty()" for f in fields if f]
        lines.append(f"{ind}if ({' && '.join(guard_parts)}) {{")

        args = []
        for f in fields:
            if f is None:
                continue
            args.append(f"{f['name']}.data()")
            args.append(f"static_cast<i_t>({f['name']}.size())")
        lines.append(f"{ind}  cpu_problem.{setter_name}({', '.join(args)});")
        lines.append(f"{ind}}}")
        lines.append("")

    # Non-grouped arrays
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        name = f["name"]
        if name in grouped_fields or f.get("skip_conversion"):
            continue
        ftype = f.get("type", "repeated double")
        afid = _field_array_id_name(f)
        setter = _default_problem_setter(f)

        enum_key = _is_repeated_enum(registry, ftype)
        if enum_key:
            edef = _lookup_enum(registry, enum_key)
            from_fn = _enum_from_proto_fn(enum_key, edef)
            cpp_type = _enum_cpp_type(enum_key, edef)
            lines.append(
                f"{ind}auto {name}_ints = get_ints(cuopt::remote::{afid});"
            )
            lines.append(f"{ind}if (!{name}_ints.empty()) {{")
            lines.append(f"{ind}  std::vector<{cpp_type}> {name};")
            lines.append(f"{ind}  {name}.reserve({name}_ints.size());")
            lines.append(f"{ind}  for (auto v : {name}_ints) {{")
            lines.append(
                f"{ind}    {name}.push_back({from_fn}(static_cast<cuopt::remote::{_enum_proto_type(enum_key, edef)}>(v)));"
            )
            lines.append(f"{ind}  }}")
            lines.append(
                f"{ind}  cpu_problem.{setter}({name}.data(), static_cast<i_t>({name}.size()));"
            )
            lines.append(f"{ind}}}")
        elif ftype == "repeated string":
            lines.append(
                f"{ind}auto {name} = get_string_list(cuopt::remote::{afid});"
            )
            lines.append(
                f"{ind}if (!{name}.empty()) {{ cpu_problem.{setter}({name}); }}"
            )
        elif ftype == "bytes":
            lines.append(
                f"{ind}auto {name}_str = get_bytes(cuopt::remote::{afid});"
            )
            lines.append(f"{ind}if (!{name}_str.empty()) {{")
            lines.append(
                f"{ind}  cpu_problem.set_{name}({name}_str.data(), static_cast<i_t>({name}_str.size()));"
            )
            lines.append(f"{ind}}}")
        elif ftype.startswith("repeated"):
            extract_fn = "get_doubles" if "double" in ftype else "get_ints"
            lines.append(
                f"{ind}auto {name} = {extract_fn}(cuopt::remote::{afid});"
            )
            lines.append(f"{ind}if (!{name}.empty()) {{")
            lines.append(
                f"{ind}  cpu_problem.{setter}({name}.data(), static_cast<i_t>({name}.size()));"
            )
            lines.append(f"{ind}}}")
        lines.append("")

    return "\n".join(lines).rstrip()


def _gen_build_array_chunk_requests(registry, indent="  "):
    """Generate body of build_array_chunk_requests()."""
    obj = registry.get("optimization_problem", {})
    ind = indent
    lines = [
        f"{ind}std::vector<cuopt::remote::SendArrayChunkRequest> requests;"
    ]
    lines.append("")
    setter_groups = obj.get("setter_groups", {})
    grouped_fields = set()
    for gdef in setter_groups.values():
        for fname in gdef.get("fields", []):
            grouped_fields.add(fname)

    def _emit_chunk_call(f, getter_expr, var_name, ii):
        ftype = f.get("type", "repeated double")
        afid = _field_array_id_name(f)

        if ftype == "repeated string":
            lines.append(f"{ii}{{")
            lines.append(f"{ii}  auto _blob = names_to_blob({getter_expr});")
            lines.append(
                f"{ii}  chunk_byte_blob(requests, cuopt::remote::{afid}, _blob, upload_id, chunk_size_bytes);"
            )
            lines.append(f"{ii}}}")
        elif ftype == "bytes":
            lines.append(f"{ii}if (!{var_name}.empty()) {{")
            lines.append(
                f"{ii}  std::vector<uint8_t> _bytes({var_name}.begin(), {var_name}.end());"
            )
            lines.append(
                f"{ii}  chunk_byte_blob(requests, cuopt::remote::{afid}, _bytes, upload_id, chunk_size_bytes);"
            )
            lines.append(f"{ii}}}")
        elif "int32" in ftype:
            lines.append(
                f"{ii}chunk_typed_array(requests, cuopt::remote::{afid}, {var_name}, upload_id, chunk_size_bytes);"
            )
        elif _is_repeated_enum(registry, ftype):
            lines.append(
                f"{ii}chunk_typed_array(requests, cuopt::remote::{afid}, {var_name}, upload_id, chunk_size_bytes);"
            )
        else:
            lines.append(
                f"{ii}chunk_typed_array(requests, cuopt::remote::{afid}, {var_name}, upload_id, chunk_size_bytes);"
            )

    # Non-grouped arrays
    for entry in obj.get("arrays", []):
        f = parse_field(entry)
        name = f["name"]
        if name in grouped_fields or f.get("skip_conversion"):
            continue
        ftype = f.get("type", "repeated double")
        getter = _default_problem_getter(f, is_scalar=False)

        enum_key = _is_repeated_enum(registry, ftype)
        if enum_key:
            edef = _lookup_enum(registry, enum_key)
            to_fn = _enum_to_proto_fn(enum_key, edef)
            afid = _field_array_id_name(f)
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto _{name} = problem.{getter};")
            lines.append(f"{ind}  if (!_{name}.empty()) {{")
            lines.append(f"{ind}    std::vector<int32_t> _{name}_ints;")
            lines.append(f"{ind}    _{name}_ints.reserve(_{name}.size());")
            lines.append(
                f"{ind}    for (const auto& v : _{name}) _{name}_ints.push_back(static_cast<int32_t>({to_fn}(v)));"
            )
            lines.append(
                f"{ind}    chunk_typed_array(requests, cuopt::remote::{afid}, _{name}_ints, upload_id, chunk_size_bytes);"
            )
            lines.append(f"{ind}  }}")
            lines.append(f"{ind}}}")
        elif ftype == "repeated string":
            _emit_chunk_call(f, f"problem.{getter}", None, ind)
        elif ftype == "bytes":
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto _{name} = problem.{getter};")
            _emit_chunk_call(f, None, f"_{name}", ind + "  ")
            lines.append(f"{ind}}}")
        else:
            lines.append(f"{ind}{{")
            lines.append(f"{ind}  auto _{name} = problem.{getter};")
            _emit_chunk_call(f, None, f"_{name}", ind + "  ")
            lines.append(f"{ind}}}")

    # Setter groups
    for gname, gdef in setter_groups.items():
        fields = [
            _find_problem_field(obj, fn) for fn in gdef.get("fields", [])
        ]
        for f in fields:
            if f is None:
                continue
            getter = _default_problem_getter(f, is_scalar=False)
            afid = _field_array_id_name(f)
            lines.append(f"{ind}{{")
            lines.append(
                f"{ind}  const auto& _{f['name']} = problem.{getter};"
            )
            lines.append(
                f"{ind}  chunk_typed_array(requests, cuopt::remote::{afid}, _{f['name']}, upload_id, chunk_size_bytes);"
            )
            lines.append(f"{ind}}}")

    lines.append("")
    lines.append(f"{ind}return requests;")
    return "\n".join(lines)


# ============================================================================
# Auto-numbering (ruamel.yaml round-trip)
# ============================================================================

# Ranges for auto-numbering.  hi=None means no upper bound (own message).
# Only solution scalars need hard caps because they share ChunkedResultHeader.
# Solution array_ids share a global ResultFieldId pool (handled separately).
FIELD_NUM_RANGES = {
    "optimization_problem.field_num": (1, None),
    "optimization_problem.array_id": (0, None),
    "lp_solution.scalars": (1000, 1999),
    "lp_solution.arrays.field_num": (1, None),
    "mip_solution.scalars": (2000, 2999),
    "mip_solution.arrays.field_num": (1, None),
    "lp_solution.warm_start.scalars": (3000, 3999),
    "lp_solution.warm_start.arrays.field_num": (1, None),
    "pdlp_settings": (1, None),
    "mip_settings": (1, None),
}


def _collect_field_nums(entries, key_name="field_num"):
    """Collect all existing field_num or array_id values from a list of field entries."""
    nums = set()
    for entry in entries:
        if isinstance(entry, dict) and len(entry) == 1:
            name = next(iter(entry))
            val = entry[name]
            if isinstance(val, dict) and key_name in val:
                nums.add(val[key_name])
    return nums


def _collect_settings_field_nums(entries):
    """Collect field_num values from settings fields (handles nesting)."""
    nums = set()
    for entry in entries:
        if isinstance(entry, dict) and len(entry) == 1:
            name = next(iter(entry))
            val = entry[name]
            if isinstance(val, list):
                nums |= _collect_settings_field_nums(val)
            elif isinstance(val, dict) and "field_num" in val:
                nums.add(val["field_num"])
    return nums


def _ruamel_insert(mapping, key, value):
    """Add a key to a CommentedMap at its conventional position.

    field_num goes first (position 0), array_id goes right after field_num,
    everything else appends."""
    if not hasattr(mapping, "insert"):
        mapping[key] = value
        return
    if key == "field_num":
        mapping.insert(0, key, value)
    elif key == "array_id":
        pos = 1 if "field_num" in mapping else 0
        mapping.insert(pos, key, value)
    else:
        mapping[key] = value


def _assign_to_field_list(entries, key_name, lo, hi, existing, label):
    """Assign missing key_name values to fields in a list. Mutates entries in-place.
    hi=None means no upper bound."""
    next_num = max(existing) + 1 if existing else lo
    assigned = 0
    for idx, entry in enumerate(entries):
        if isinstance(entry, str):
            continue
        if not isinstance(entry, dict) or len(entry) != 1:
            continue
        name = next(iter(entry))
        val = entry[name]
        if val is None:
            try:
                from ruamel.yaml.comments import CommentedMap

                entry[name] = CommentedMap([(key_name, next_num)])
            except ImportError:
                entry[name] = {key_name: next_num}
            existing.add(next_num)
            next_num += 1
            assigned += 1
        elif isinstance(val, dict) and key_name not in val:
            _ruamel_insert(val, key_name, next_num)
            existing.add(next_num)
            next_num += 1
            assigned += 1
    if hi is not None and next_num - 1 > hi and assigned > 0:
        raise ValueError(
            f"Range overflow in {label}: assigned {next_num - 1} exceeds max {hi}"
        )
    return assigned


def _assign_to_settings_fields(entries, lo, hi, existing, label):
    """Assign missing field_num to settings fields (handles nesting). Mutates in-place.
    hi=None means no upper bound."""
    try:
        from ruamel.yaml.comments import CommentedMap as _CMap
    except ImportError:
        _CMap = None
    next_num = max(existing) + 1 if existing else lo
    assigned = 0
    for entry in entries:
        if not isinstance(entry, dict) or len(entry) != 1:
            continue
        name = next(iter(entry))
        val = entry[name]
        if isinstance(val, list):
            sub_assigned = _assign_to_settings_fields(
                val, lo, hi, existing, f"{label}.{name}"
            )
            assigned += sub_assigned
            next_num = max(existing) + 1 if existing else next_num
        elif val is None:
            if _CMap is not None:
                entry[name] = _CMap([("field_num", next_num)])
            else:
                entry[name] = {"field_num": next_num}
            existing.add(next_num)
            next_num += 1
            assigned += 1
        elif isinstance(val, dict) and "field_num" not in val:
            _ruamel_insert(val, "field_num", next_num)
            existing.add(next_num)
            next_num += 1
            assigned += 1
    if hi is not None and next_num - 1 > hi and assigned > 0:
        raise ValueError(
            f"Range overflow in {label}: assigned {next_num - 1} exceeds max {hi}"
        )
    return assigned


def _normalize_bare_strings(entries):
    """Convert bare string entries in a field list to single-key dicts.
    This lets the auto-numbering logic treat them uniformly.

    Avoids modifying CommentedSeq comment attributes (ca.items) to prevent
    corrupting ruamel.yaml's internal comment tracking on dump."""
    try:
        from ruamel.yaml.comments import CommentedMap

        mk_inner = CommentedMap

        def mk_outer(name, inner):
            return CommentedMap([(name, inner)])

    except ImportError:
        mk_inner = dict

        def mk_outer(name, inner):
            return {name: inner}

    for idx, entry in enumerate(entries):
        if isinstance(entry, str):
            entries[idx] = mk_outer(entry, mk_inner())


_STRIP_RE = re.compile(r"^ +(?:field_num|array_id): +\d+ *\n", re.MULTILINE)


def strip_field_numbers_text(path):
    """Remove field_num/array_id lines from the registry via text substitution.

    Pure text operation — guaranteed to preserve all comments and formatting.
    Returns the number of lines removed."""
    with open(path) as f:
        original = f.read()
    stripped, count = _STRIP_RE.subn("", original)
    if count > 0:
        with open(path, "w") as f:
            f.write(stripped)
    return count


def _dump_and_verify(ryaml, data, path):
    """Dump YAML data to a string buffer, verify comments survived, then write.

    Never truncates the original file until the output is validated."""
    from io import StringIO

    with open(path) as f:
        original = f.read()
    original_comments = [
        line for line in original.splitlines() if line.lstrip().startswith("#")
    ]

    buf = StringIO()
    ryaml.dump(data, buf)
    written = buf.getvalue()
    written_comments = [
        line for line in written.splitlines() if line.lstrip().startswith("#")
    ]

    if len(written_comments) < len(original_comments):
        print(
            f"ERROR: comment loss detected in {path} "
            f"({len(original_comments)} → {len(written_comments)} comment lines). "
            f"File not modified.",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(path, "w") as f:
        f.write(written)


def _registry_has_field_numbers(registry):
    """Check if the registry has at least one field_num or array_id assigned."""
    for section_key in list(registry.keys()):
        section = registry.get(section_key)
        if not isinstance(section, dict):
            continue
        for list_key in ["scalars", "arrays"]:
            for nums in [
                _collect_field_nums(section.get(list_key, []), "field_num"),
                _collect_field_nums(section.get(list_key, []), "array_id"),
            ]:
                if nums:
                    return True
        if "fields" in section:
            if _collect_settings_field_nums(section["fields"]):
                return True
        sub = section.get("warm_start")
        if isinstance(sub, dict):
            for list_key in ["scalars", "arrays"]:
                for key in ["field_num", "array_id"]:
                    if _collect_field_nums(sub.get(list_key, []), key):
                        return True
    return False


def auto_assign_field_numbers(data):
    """Walk the registry and assign missing field_num / array_id values.

    Operates on ruamel.yaml CommentedMap data in-place.
    Returns the total number of assignments made.
    """
    # Normalize bare string entries to dicts before processing
    for section_key in list(data.keys()):
        section = data.get(section_key)
        if not isinstance(section, dict):
            continue
        for list_key in ["scalars", "arrays", "fields"]:
            entries = section.get(list_key)
            if entries:
                _normalize_bare_strings(entries)
        for sub_key in ["warm_start"]:
            sub = section.get(sub_key)
            if isinstance(sub, dict):
                for list_key in ["scalars", "arrays"]:
                    entries = sub.get(list_key)
                    if entries:
                        _normalize_bare_strings(entries)

    total = 0

    for section_key in ["optimization_problem"]:
        section = data.get(section_key)
        if not section:
            continue

        # field_num — single contiguous pool across scalars and arrays
        scalars = section.get("scalars", [])
        arrays = section.get("arrays", [])
        lo, hi = FIELD_NUM_RANGES[f"{section_key}.field_num"]
        existing_fn = _collect_field_nums(
            scalars, "field_num"
        ) | _collect_field_nums(arrays, "field_num")
        total += _assign_to_field_list(
            scalars,
            "field_num",
            lo,
            hi,
            existing_fn,
            f"{section_key}.scalars.field_num",
        )
        total += _assign_to_field_list(
            arrays,
            "field_num",
            lo,
            hi,
            existing_fn,
            f"{section_key}.arrays.field_num",
        )

        # array_id — separate namespace
        lo, hi = FIELD_NUM_RANGES[f"{section_key}.array_id"]
        existing_aid = _collect_field_nums(arrays, "array_id")
        total += _assign_to_field_list(
            arrays,
            "array_id",
            lo,
            hi,
            existing_aid,
            f"{section_key}.arrays.array_id",
        )

    # Collect all solution array_ids into a shared pool (ResultFieldId is global).
    shared_result_ids = set()
    all_solution_array_lists = []
    for section_key in ["lp_solution", "mip_solution"]:
        section = data.get(section_key)
        if not section:
            continue
        arr = section.get("arrays", [])
        shared_result_ids |= _collect_field_nums(arr, "array_id")
        all_solution_array_lists.append((section_key, arr))
        ws = section.get("warm_start")
        if ws:
            ws_arr = ws.get("arrays", [])
            shared_result_ids |= _collect_field_nums(ws_arr, "array_id")
            all_solution_array_lists.append(
                (f"{section_key}.warm_start", ws_arr)
            )

    for section_key in ["lp_solution", "mip_solution"]:
        section = data.get(section_key)
        if not section:
            continue

        # Scalars — field_num (range-bound for ChunkedResultHeader)
        scalars = section.get("scalars", [])
        lo, hi = FIELD_NUM_RANGES[f"{section_key}.scalars"]
        existing = _collect_field_nums(scalars, "field_num")
        total += _assign_to_field_list(
            scalars, "field_num", lo, hi, existing, f"{section_key}.scalars"
        )

        # Arrays — field_num (per-message, no cap)
        arrays = section.get("arrays", [])
        arr_fn_range = FIELD_NUM_RANGES.get(
            f"{section_key}.arrays.field_num", (1, None)
        )
        existing_fn = _collect_field_nums(arrays, "field_num")
        total += _assign_to_field_list(
            arrays,
            "field_num",
            arr_fn_range[0],
            arr_fn_range[1],
            existing_fn,
            f"{section_key}.arrays.field_num",
        )

        # Arrays — array_id (shared ResultFieldId pool, no cap)
        total += _assign_to_field_list(
            arrays,
            "array_id",
            0,
            None,
            shared_result_ids,
            f"{section_key}.arrays.array_id",
        )

        # Warm start
        ws = section.get("warm_start")
        if ws:
            ws_scalars = ws.get("scalars", [])
            lo, hi = FIELD_NUM_RANGES.get(
                f"{section_key}.warm_start.scalars", (3000, 3999)
            )
            existing = _collect_field_nums(ws_scalars, "field_num")
            total += _assign_to_field_list(
                ws_scalars,
                "field_num",
                lo,
                hi,
                existing,
                f"{section_key}.warm_start.scalars",
            )

            ws_arrays = ws.get("arrays", [])
            ws_fn_range = FIELD_NUM_RANGES.get(
                f"{section_key}.warm_start.arrays.field_num", (1, None)
            )
            existing_fn = _collect_field_nums(ws_arrays, "field_num")
            total += _assign_to_field_list(
                ws_arrays,
                "field_num",
                ws_fn_range[0],
                ws_fn_range[1],
                existing_fn,
                f"{section_key}.warm_start.arrays.field_num",
            )

            # WS arrays — array_id (shared ResultFieldId pool)
            total += _assign_to_field_list(
                ws_arrays,
                "array_id",
                0,
                None,
                shared_result_ids,
                f"{section_key}.warm_start.arrays.array_id",
            )

    for section_key in ["pdlp_settings", "mip_settings"]:
        section = data.get(section_key)
        if not section:
            continue
        fields = section.get("fields", [])
        lo, hi = FIELD_NUM_RANGES[section_key]
        existing = _collect_settings_field_nums(fields)
        total += _assign_to_settings_fields(
            fields, lo, hi, existing, section_key
        )

    return total


# ============================================================================
# main()
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description="Generate conversion code from field registry"
    )
    parser.add_argument(
        "--registry",
        default=str(Path(__file__).parent / "field_registry.yaml"),
    )
    parser.add_argument(
        "--output-dir", default=str(Path(__file__).parent / "generated")
    )
    parser.add_argument(
        "--auto-number",
        action="store_true",
        help="Auto-assign missing field_num and array_id values, writing "
        "them back to the registry YAML (preserves comments/formatting).",
    )
    parser.add_argument(
        "--strip",
        action="store_true",
        help="Remove all field_num and array_id values from the registry YAML "
        "and exit. Useful before committing a minimal registry.",
    )
    args = parser.parse_args()

    if args.strip:
        n = strip_field_numbers_text(args.registry)
        if n > 0:
            print(f"  stripped {n} field number(s) from {args.registry}")
        else:
            print("  no field numbers to strip")
        sys.exit(0)

    if args.auto_number:
        try:
            from ruamel.yaml import YAML
        except ImportError:
            print(
                "ERROR: --auto-number requires ruamel.yaml. "
                "Install with: pip install ruamel.yaml",
                file=sys.stderr,
            )
            sys.exit(1)

        ryaml = YAML(typ="rt")
        ryaml.preserve_quotes = True
        with open(args.registry) as f:
            rt_data = ryaml.load(f)

        n = auto_assign_field_numbers(rt_data)
        if n > 0:
            _dump_and_verify(ryaml, rt_data, args.registry)
            print(f"  auto-numbered {n} field(s) in {args.registry}")
        else:
            print("  all field numbers already assigned")

    with open(args.registry) as f:
        registry = yaml.safe_load(f)

    if not _registry_has_field_numbers(registry):
        print(
            "ERROR: Registry has no field_num or array_id values assigned.\n"
            "Run with --auto-number to assign them before generating.",
            file=sys.stderr,
        )
        sys.exit(1)

    outdir = args.output_dir

    # Proto reference .inc files
    write_file(
        os.path.join(outdir, "generated_result_enums.proto.inc"),
        HEADER
        + "// ResultFieldId enum entries\n"
        + generate_proto_result_enums(registry)
        + "\n",
    )

    # Settings conversion .inc
    for key, label in [("pdlp_settings", "pdlp"), ("mip_settings", "mip")]:
        if key in registry:
            obj = registry[key]
            write_file(
                os.path.join(
                    outdir, f"generated_{label}_settings_to_proto.inc"
                ),
                HEADER
                + generate_settings_to_proto_body(registry, key, obj)
                + "\n",
            )
            write_file(
                os.path.join(
                    outdir, f"generated_proto_to_{label}_settings.inc"
                ),
                HEADER
                + generate_proto_to_settings_body(registry, key, obj)
                + "\n",
            )

    # Full data proto
    write_file(
        os.path.join(outdir, "cuopt_remote_data.proto"),
        generate_data_proto(registry),
    )

    # Per-domain enum converters
    for domain in ("settings", "solution", "problem"):
        write_file(
            os.path.join(outdir, f"generated_enum_converters_{domain}.inc"),
            HEADER + generate_enum_converters_inc(registry, domain) + "\n",
        )

    # Solution conversion .inc files
    for key, label in [("lp_solution", "lp"), ("mip_solution", "mip")]:
        obj = registry.get(key)
        if not obj:
            continue
        write_file(
            os.path.join(outdir, f"generated_{label}_solution_to_proto.inc"),
            HEADER + _gen_solution_to_proto(registry, key, obj) + "\n",
        )
        write_file(
            os.path.join(outdir, f"generated_proto_to_{label}_solution.inc"),
            HEADER + _gen_proto_to_solution(registry, key, obj) + "\n",
        )
        write_file(
            os.path.join(outdir, f"generated_{label}_chunked_header.inc"),
            HEADER + _gen_chunked_header(registry, key, obj) + "\n",
        )
        write_file(
            os.path.join(outdir, f"generated_collect_{label}_arrays.inc"),
            HEADER + _gen_collect_arrays(registry, key, obj) + "\n",
        )
        write_file(
            os.path.join(outdir, f"generated_chunked_to_{label}_solution.inc"),
            HEADER + _gen_chunked_to_solution(registry, key, obj) + "\n",
        )
        write_file(
            os.path.join(outdir, f"generated_estimate_{label}_size.inc"),
            HEADER + _gen_estimate_size(registry, key, obj) + "\n",
        )

    # Problem conversion .inc files
    if "optimization_problem" in registry:
        write_file(
            os.path.join(outdir, "generated_problem_to_proto.inc"),
            HEADER + _gen_problem_to_proto(registry) + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_proto_to_problem.inc"),
            HEADER + _gen_proto_to_problem(registry) + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_estimate_problem_size.inc"),
            HEADER + _gen_estimate_problem_size(registry) + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_populate_chunked_header_lp.inc"),
            HEADER + _gen_populate_chunked_header(registry, "lp") + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_populate_chunked_header_mip.inc"),
            HEADER + _gen_populate_chunked_header(registry, "mip") + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_chunked_header_to_problem.inc"),
            HEADER + _gen_chunked_header_to_problem(registry) + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_chunked_arrays_to_problem.inc"),
            HEADER + _gen_chunked_arrays_to_problem(registry) + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_build_array_chunks.inc"),
            HEADER + _gen_build_array_chunk_requests(registry) + "\n",
        )
        write_file(
            os.path.join(outdir, "generated_array_field_element_size.inc"),
            HEADER + generate_array_field_element_size_inc(registry) + "\n",
        )

    print(f"\nDone! Generated {len(os.listdir(outdir))} files in: {outdir}")


if __name__ == "__main__":
    main()
